categories:
  - name: "5-6 ans"
    minage: 5
    maxage: 6
    mixte: true
  - name: "7-8 ans"
    minage: 7
    maxage: 8
    mixte: true
  - name: "9-10 ans"
    minage: 9
    maxage: 10
    mixte: true
  - name: "11-14 ans"
    minage: 11
    maxage: 14
    mixte: false
typecompetition:
  - name: "C l'fun"
    numero_bonnet: true
    max_pat: 5
    min_derniere: 2
  - name: "Liliane-Lambert"
    numero_bonnet: false
    max_pat: 15
    min_derniere: 10
division: Régional